spring.application.name=moneymap-backend
spring.profiles.default=dev
server.port=${PORT:8080}

# JWT CONFIG
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}
app.jwt.refreshExpiration=${APP_JWT_REFRESH_EXPIRATION:604800000}

spring.jpa.open-in-view=false
